version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      
  # Maintain dependencies for hex
  - package-ecosystem: "mix"
    directory: "/backend"
    schedule:
      interval: "weekly"
