version: "3.7"

services:
  redis:
    image: redis:7.0.11
    container_name: "tenantee_redis"
    command: /bin/sh -c "redis-server --requirepass tenantee_redis"
    ports:
      - "6379:6379"

  db:
    image: postgres:14.2-alpine
    container_name: "tenantee_postgres"
    environment:
      - POSTGRES_USER=tenantee
      - POSTGRES_PASSWORD=tenantee
      - POSTGRES_DB=tenantee_dev
    ports:
      - "5432:5432"
