version: "3.7"

services:
  backend:
    build: 
      context: ./backend
      args:
        - PHOENIX_VERSION=1.6.15
    environment:
      - DB_PREFIX=${DB_PREFIX}
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    command: 
      - "./run.sh"
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"

  db:
    image: postgres:14.2-alpine
    container_name: "tenantee_postgres"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_PREFIX}_dev
    ports:
      - "5432:5432"
