on:
  pull_request:
    branches:
      - dev
      - master
    paths:
      - 'frontend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Node ${{matrix.node}}
    strategy:
      matrix:
        node: [18.12.1, 19.1.0]
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node}}
      - run: cd frontend && npm ci
      - run: cd frontend && npm run lint
      - run: cd frontend && npm run build
      - run: cd frontend && npm run cypress
